app-ols-integration/main/default/objects/OLS_Cron_Job_Detail__mdt/OLS_Cron_Job_Detail__mdt.object-meta.xml
<CustomObject>
    <description>Cron job details for OLS to easily adjust cron job details in production since both jobs are in an unlocked package and are self scheduled within the package.

This is specifically for the Bounce Back Report and Email Validation jobs. Contains the job name, cron expression and &quot;minutes from now&quot; for dev purposes.

If someone needs to change when these job runs simply change the expression here and delete the current job.</description>
    <label>OLS Cron Job Detail</label>
    <pluralLabel>OLS Cron Job Details</pluralLabel>
</CustomObject>

app-ols-integration/main/default/objects/OLS_Cron_Job_Detail__mdt/fields/Cron_Expression__c.field-meta.xml
<CustomField>
    <fullName>Cron_Expression__c</fullName>
    <description>In production this is the cron expression for when the OLS integration Salesforce application schedules a job  programmatically.</description>
    <inlineHelpText>In production this is the cron expression for when the OLS integration Salesforce application schedules a job  programmatically.</inlineHelpText>
    <label>Cron Expression</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Cron_Job_Detail__mdt/fields/Job_Name__c.field-meta.xml
<CustomField>
    <fullName>Job_Name__c</fullName>
    <description>The name that will show up as the Job Name in the list of scheduled apex jobs.</description>
    <inlineHelpText>The name that will show up as the Job Name in the list of scheduled apex jobs.</inlineHelpText>
    <label>Job Name</label>
    <length>125</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Cron_Job_Detail__mdt/fields/Minutes_From_Now__c.field-meta.xml
<CustomField>
    <fullName>Minutes_From_Now__c</fullName>
    <description>In development orgs this will be how many minutes for now the job should run when created by the OLS integration salesforce application.</description>
    <inlineHelpText>In development orgs this will be how many minutes for now the job should run when created by the OLS integration salesforce application.</inlineHelpText>
    <label>Minutes From Now</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

app-ols-integration/main/default/classes/OLSCronJobHelper.cls
/**
 * @name OLSCronJobHelper
 * @description internally creates cron jobs for this application, the OLS integration application.
 * 
 * @author Creed Interactive (Andrew Frederick) July 2022
 */
public with sharing class OLSCronJobHelper {
  
/**
 * FIELDS
 */

    private static OLS_Cron_Job_Detail__mdt bounceReportCronJobDetail {get;set;}
    private static OLS_Cron_Job_Detail__mdt emailValidationCronJobDetail {get;set;}

    private static Boolean isDev {get;set;}

    static {

        isDev = [SELECT isSandBox FROM Organization LIMIT 1].IsSandbox;

        try {

            Map<String, OLS_Cron_Job_Detail__mdt> cronJobDetails = OLS_Cron_Job_Detail__mdt.getAll();
    
            bounceReportCronJobDetail = cronJobDetails.get('Bounce_Report');
            emailValidationCronJobDetail = cronJobDetails.get('Email_Validation');

        } catch( Exception e ){
            creedint.CreedExceptionHandler handler = new creedint.CreedExceptionHandler(e);
            handler.handle();
        }
    }

/**
 * ACTION METHODS
 */

    /**
     * @name scheduleBounceBackReportJob
     * @description schedules the job to email bounce reports to selected individuals if there isn't one already.
     * @param none
     * @return none
     */
    public static void scheduleBounceBackReportJob(){
        if( getJob('OLSBounceReportJob') != null ){ return; }

        scheduleJob( bounceReportCronJobDetail.Job_Name__c, getCronExpression( bounceReportCronJobDetail ), new OLSBounceReportJob() );
    }

     /**
     * @name scheduleBounceEmailValidationJob
     * @description schedules the job to validate OLS customer emails.
     * @param none
     * @return none
     */
    public static void scheduleBounceEmailValidationJob(){
        if( getJob('OLSEmailValidation') != null ){ return; }

        scheduleJob( emailValidationCronJobDetail.Job_Name__c, getCronExpression( emailValidationCronJobDetail ), new OLSEmailValidation() );
    }

    /**
     * @name scheduleJob
     * @description schedules actual job
     * @param String jobName
     * @param String cronExpression
     * @param Schedulable schedulable
     * @return none
     */
    private static void scheduleJob( String jobName, String cronExpression, Schedulable schedulable ){

        try {

            System.schedule(jobName, cronExpression, schedulable);

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler(e);
            handler.handle();
        }
    }

/**
 * UTILITY METHODS
 */

     /**
     * @name getCronExpression
     * @description gets cron expression from detail metadata type (e.g. every wednesday = '0 0 6 ? * WED')
     * @param Cron_Job_Detail__mdt detail
     * @return String
     */
    private static String getCronExpression( OLS_Cron_Job_Detail__mdt detail ){
        String cronExpression;

        if( isDev ){    
            cronExpression = OLSUtil.getMinutesFromNow( (Integer) detail.Minutes_From_Now__c ); 
        } else {
            cronExpression = detail.Cron_Expression__c;
        }

        return cronExpression;
    }

/**
 * QUERY METHODS
 */

    /**
     * @name getJob
     * @description get job by scheduable class to see if the job already exists
     * @param String className
     * @return none
     */
    private static AsyncApexJob getJob( String className ){
        AsyncApexJob job;

        try {

            job = [SELECT
                    Id
                        FROM AsyncApexJob
                        WHERE ApexClass.Name = :className
                        AND JobType = 'ScheduledApex'
                        AND Status != 'Aborted'
                        AND Status != 'Completed'
                        AND Status != 'Failed'
                        LIMIT 1];

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler(e);
            handler.debug();
        }

        return job;
    }
}