app-ols-integration/main/default/objects/Contact/fields/Brochure_Key__c.field-meta.xml
<CustomField>
    <fullName>Brochure_Key__c</fullName>
    <description>This is the name of a file stored. This file represents a pdf brochure that is sent out in a welcome email to a new Online Store Customer.</description>
    <inlineHelpText>This is the name of a file stored. This file represents a pdf brochure that is sent out in a welcome email to a new Online Store Customer.</inlineHelpText>
    <label>Brochure Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/State_Acronym__c.field-meta.xml
<CustomField>
    <fullName>State_Acronym__c</fullName>
    <description>The state acronym for Online Store Customer. This is used to determine what welcome email to send out.</description>
    <inlineHelpText>The state acronym for Online Store Customer. This is used to determine what welcome email to send out.</inlineHelpText>
    <label>State Acronym</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/ContentVersion/fields/Brochure_Coverage_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Brochure_Coverage_Start_Date__c</fullName>
    <description>This is the coverage start date that a brochure for a certain brochure key should begin being used in circulation.</description>
    <inlineHelpText>This is the coverage start date that a brochure for a certain brochure key should begin being used in circulation.</inlineHelpText>
    <label>Brochure Coverage Start Date</label>
    <type>Date</type>
</CustomField>

app-ols-integration/main/default/objects/ContentVersion/fields/Brochure_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Brochure_Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For OLS welcome email brochures. If Inactive this Brochure will not be used in system generated welcome emails.</description>
    <inlineHelpText>If Inactive this Brochure will not be used in system generated welcome emails.</inlineHelpText>
    <label>Brochure Inactive</label>
    <type>Checkbox</type>
</CustomField>

app-ols-integration/main/default/objects/ContentVersion/fields/Brochure_Key__c.field-meta.xml
<CustomField>
    <fullName>Brochure_Key__c</fullName>
    <description>This aids in finding files to send in welcome emails for Online Store Customers.</description>
    <label>Brochure Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Product_Setting__mdt/OLS_Product_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This is to help the OLS app decide certain pathways based on the product that was sold to the customer. (e.g. if vision was sold use a vision email template.)</description>
    <label>OLS Product Setting</label>
    <pluralLabel>OLS Product Settings</pluralLabel>
</CustomObject>

app-ols-integration/main/default/objects/OLS_Welcome_Email_Setting__mdt/OLS_Welcome_Email_Setting__mdt.object-meta.xml
<CustomObject>
    <description>These settings will help determine, based on state, which what assets (e.g. template, from address, etc.) to use within welcome emails.</description>
    <label>OLS Welcome Email Setting</label>
    <pluralLabel>OLS Welcome Email Setting</pluralLabel>
</CustomObject>

app-ols-integration/main/default/objects/OLS_Welcome_Email_Setting__mdt/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <description>The developer name of the email template for which ever state the OLS customer resides in.</description>
    <inlineHelpText>The developer name of the email template for which ever state the OLS customer resides in.</inlineHelpText>
    <label>Email Template Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Welcome_Email_Setting__mdt/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <description>Address used as from address in welcome email. MUST match a verified Organization Wide Address.</description>
    <inlineHelpText>Address used as from address in welcome email. MUST match a verified Organization Wide Address.</inlineHelpText>
    <label>From Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Welcome_Email_Setting__mdt/fields/Multiple_Products_Sold__c.field-meta.xml
<CustomField>
    <fullName>Multiple_Products_Sold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked if the state sells multiple products (e.g. Dental and Vision) in order to make possible things like using different email templates for different products purchased.</description>
    <inlineHelpText>This is checked if the state sells multiple products (e.g. Dental and Vision) in order to make possible things like using different email templates for different products purchased.</inlineHelpText>
    <label>Multiple Products Sold</label>
    <type>Checkbox</type>
</CustomField>

app-ols-integration/main/default/objects/OLS_Welcome_Email_Setting__mdt/fields/Supplied_State_Acronym__c.field-meta.xml
<CustomField>
    <fullName>Supplied_State_Acronym__c</fullName>
    <description>This is the &apos;state acronym&apos; that is supplied from the OLS WebApp. It&apos;s values don&apos;t necessarily match that of an exact state acronym but the values supplied are SOLELY responsible for determine what welcome email template is used.</description>
    <inlineHelpText>This is the &apos;state acronym&apos; that is supplied from the OLS WebApp. It&apos;s values don&apos;t necessarily match that of an exact state acronym but the values supplied are SOLELY responsible for determine what welcome email template is used.</inlineHelpText>
    <label>Supplied State Acronym</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/classes/OLSEmailCore.cls
/**
 * @name OLSEmailCore
 * @description this is the core class that generates and sends welcome emails
 * 
 * @author Creed Interactive (Andrew Frederick) October 2021
 */
public without sharing class OLSEmailCore {

/**
 * FEILDS
 */

    private Contact[] customers {
        get {
            if( customers == null ){
                customers = new Contact[]{};
            }
            return customers;
        }
        set;
    }

    private Map<String, Contact[]> customersByTemplateName {
        get {
            if( customersByTemplateName == null ){
                customersByTemplateName = new Map<String, Contact[]>();
            }
            return customersByTemplateName;
        }
        set;
    }

    private Map<String, String> fromAddressesByTemplateName {
        get {
            if( fromAddressesByTemplateName == null ){
                fromAddressesByTemplateName = new Map<String, String>();
            }
            return fromAddressesByTemplateName;
        }
        set;
    }

    // Custom Metadata Type to determine what assets (e.g. Template, Org Wide Address for from adress, etc.) to use in welcom email
    private static Map<String, OLS_Welcome_Email_Setting__mdt> emaialSettingsByState = new Map<String, OLS_Welcome_Email_Setting__mdt>();

    private static String[] products = new String[]{};

    static {

        try {

            OLS_Welcome_Email_Setting__mdt[] emailSettings = OLS_Welcome_Email_Setting__mdt.getAll().values();

            for( OLS_Welcome_Email_Setting__mdt setting : emailSettings ){
                emaialSettingsByState.put( setting.Supplied_State_Acronym__c, setting );
            }

            OLS_Product_Setting__mdt[] productSettings = OLS_Product_Setting__mdt.getAll().values();

            for( OLS_Product_Setting__mdt setting : productSettings ){
                if( setting.isActive__c ){
                    products.add( setting.Product_Name__c );
                }
            }

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler(e);
            handler.handle();
        }
    }

    private static final String STATE_ACRONYM_ERROR = 'There were OLS customers that were registered but no email sent. Most likely due to state acronym values not matching between WebApps and Salesforce OLS Welcome Email Settings Custom Metadata Type.';

/**
 * CONSTUCTORS
 */

    public OLSEmailCore( Contact[] customers ){
        this.customers = customers;

        setCustomersByTemplateName();
    }

/**
 * ACTION METHODS
 */

    /**
     * @name sendEmails
     * @description actually sends the emails using the Creed Email App
     * @param none
     * @return none
     */
    public void sendEmails(){
        if( customers.isEmpty() ){ return; }

        try {

            EmailParcel[] parcels = getParcels();
    
            EmailFactoryOutbound emailFactory = new EmailFactoryOutbound( parcels );
            emailFactory.build();

            EmailPost emailPost = new EmailPost( emailFactory );
            emailPost.addTriggerHook( new OLSTriggerHook() );
            emailPost.post();

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler( e , customers );
            handler.handle();
        }
    }

/**
 * UTILITY METHODS
 */

    /**
     * @name setCustomersByTemplateName
     * @description loops through all the settings by state and grabs an customers by state. Puts the customers into an Email App parcel factory then
     * extracts the parcels fromt the factory for emailing.
     * @param none
     * @return none
     */
    private void setCustomersByTemplateName(){

        try{

            for( Contact customer : customers ){

                OLS_Welcome_Email_Setting__mdt setting = emaialSettingsByState.get( customer.State_Acronym__c );

                if( setting == null ){
                    throw new TemplateException( STATE_ACRONYM_ERROR );
                }
    
                String templateName = setting.Email_Template_Name__c;
    
                // if the brochure key contains a product above. let's augment the template name to include the product and we'll name the email templates accordingly

                if( setting.Multiple_Products_Sold__c ){

                    for( String product : products ){
                        if( customer.Brochure_Key__c.containsIgnoreCase( product ) && !String.isBlank(templateName) ){
                            templateName += '_' + product;
                            break;
                        }
                    }
                } 

                if( String.isBlank(templateName) ){
                    throw new TemplateException( 'No template name found for this OLS contact in OLSEmailCore.cls: ' + JSON.serialize(customer) );
                }
                
                fromAddressesByTemplateName.put( templateName, setting.From_Address__c );

                if( customersByTemplateName.containsKey( templateName ) ){
                    customersByTemplateName.get( templateName ).add( customer );
                } else {
                    customersByTemplateName.put( templateName, new Contact[]{ customer } );
                }
            }

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler( e , customers );
            handler.handle();
        }
    }

    /**
     * @name getParcels
     * @description loops through all the settings by state and grabs an customers by state. Puts the customers into an Email App parcel factory then
     * extracts the parcels fromt the factory for emailing.
     * @param none
     * @return EmailParcel[] parcels
     */
    private EmailParcel[] getParcels(){

        ContentVersion[] versions = getContentVersions();

        EmailParcel[] parcels = new EmailParcel[]{};

        for( String templateName : customersByTemplateName.keySet() ){

            Contact[] customersToUse = customersByTemplateName.get(templateName);

            EmailParcelFactoryOLS parcelFactory = new EmailParcelFactoryOLS( customersToUse );
            parcelFactory.setTemplate( templateName );
            parcelFactory.setOrgWideEmailAddressId( fromAddressesByTemplateName.get(templateName) );
            parcelFactory.addAttachmentsByName( versions );
            parcelFactory.build();

            parcels.addAll( parcelFactory.getParcels() );
        }

        return parcels;
    }

/**
 * QUERY METHODS
 */

    /**
     * @name getContentVersions
     * @description gets Brochure PDFs for email's attachment
     * @param none
     * @return ContentVersion[] versions
     */
    private ContentVersion[] getContentVersions(){
        ContentVersion[] versions = new ContentVersion[]{};

        String[] brochureKeys = new String[]{};

        for( Contact customer : customers ){

            if( !String.isBlank( customer.Brochure_Key__c ) ){
                brochureKeys.add( customer.Brochure_Key__c );
            }
        }

        try {

            if( brochureKeys.isEmpty() ){
                throw new BrochureKeyException('No brochure keys associated with these customer records.');
            }

            versions.addAll([SELECT
                Id,
                Title,
                PathOnClient,
                VersionData,
                Brochure_Key__c,
                Brochure_Coverage_Start_Date__c
                    FROM ContentVersion
                    WHERE Brochure_Key__c IN :brochureKeys
                    AND Brochure_Inactive__c = false]);

        } catch( Exception e ){
            CreedExceptionHandler handler = new CreedExceptionHandler(e, customers);
            handler.handle();
        }

        return versions;
    }

/**
 * CLASSES
 */

    public class BrochureKeyException extends Exception {}
    public class TemplateException extends Exception {}
}