app-ols-integration/main/default/objects/Contact/fields/Brochure_Key__c.field-meta.xml
<CustomField>
    <fullName>Brochure_Key__c</fullName>
    <description>This is the name of a file stored. This file represents a pdf brochure that is sent out in a welcome email to a new Online Store Customer.</description>
    <inlineHelpText>This is the name of a file stored. This file represents a pdf brochure that is sent out in a welcome email to a new Online Store Customer.</inlineHelpText>
    <label>Brochure Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Brochure_URL__c.field-meta.xml
<CustomField>
    <fullName>Brochure_URL__c</fullName>
    <description>URL that can be used to link to brochures in welcome emails for Online Store Customers.</description>
    <label>Brochure URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/CAID__c.field-meta.xml
<CustomField>
    <fullName>CAID__c</fullName>
    <description>An Id that is generated by DDMI when an Online Store Customer and their payment method has been approved. It is a unique External Id.</description>
    <externalId>true</externalId>
    <inlineHelpText>An Id that is generated by DDMI when an Online Store Customer and their payment method has been approved. It is a unique External Id.</inlineHelpText>
    <label>CAID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <description>For Online Store Customer record type. This is the customer Id that is store over at DDMI after an Online Store Customer is processed by DDMI&apos;s application.</description>
    <externalId>true</externalId>
    <label>Customer Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>For Online Store Customer record type.</description>
    <label>Payment Frequency</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Payment_Successful__c.field-meta.xml
<CustomField>
    <fullName>Payment_Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For the Online Store Customer record type. Indicates whether or not the payment was successful.</description>
    <inlineHelpText>Indicates whether or not the payment was successful.</inlineHelpText>
    <label>Payment Successful</label>
    <type>Checkbox</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>For Online Store Customer record type. The way by which an Online Store Customer will pay their bill.</description>
    <inlineHelpText>The way by which an Online Store Customer will pay their bill.</inlineHelpText>
    <label>Payment Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/fields/Product_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Product_Purchased__c</fullName>
    <description>Product Purchased by a Contact that is now an Online Store Customer.</description>
    <inlineHelpText>Product Purchased by a Contact that is now an Online Store Customer.</inlineHelpText>
    <label>Product Purchased</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

app-ols-integration/main/default/objects/Contact/recordTypes/Online_Store_Customer.recordType-meta.xml
<RecordType>
    <fullName>Online_Store_Customer</fullName>
    <active>true</active>
    <description>This contact is an individual who purchased a product or products from DDMN&apos;s WebApp&apos;s Online Store</description>
    <label>Online Store Customer</label>
</RecordType>

app-ols-integration/main/default/classes/OLSCustomerRestServiceHelper.cls
/**
 * @name OLSCustomerRestServiceHelper
 * @description this class helps parse the JSON that is delivered to the apex rest service class OnlineStoreCustomerRestService.cls
 * as well as deliver contact that is loaded with all the values from the parsed JSON.
 * 
 * @author Creed Interactive (Andrew Frederick) October 2021
 */
public with sharing class OLSCustomerRestServiceHelper {

/**
 * FIELDS
 */

    public String requestBody;
    public ClientSideCustomer customer;

/**
* CONSTRUCTOR
*/

    public OLSCustomerRestServiceHelper( String b ) {
        requestBody = b;
    }

/**
* ACTION METHODS
*/  
    /**
     * @name parseRequest
     * @description parses the JSON sent in the request to the OnlineStoreCustomerRestService.cls
     * @param ClientSideCustomer customer
     * @return Contact
     */
    public void parseRequest(){
        customer = (ClientSideCustomer) JSON.deserialize( requestBody, ClientSideCustomer.class );
    }

    /**
     * @name getNewContact
     * @description gets Instance of contact (Online Store Customer) for insert
     * @param ClientSideCustomer customer
     * @return Contact
     */
    public Contact getNewContact(){
        if( customer == null ) return null;

        Boolean paymentSuccessful = customer.paymentDetails.paymentSuccessful == 'true' ? true : customer.paymentDetails.paymentSuccessful == 'false' ? false : null;

        Contact newContact = new Contact(
            FirstName = customer.firstName,
            LastName = customer.lastName,
            Email = customer.email,
            Phone = customer.phone,
            MailingCity = customer.address.city,
            MailingState = customer.address.state,
            MailingPostalCode = customer.address.zip,
            Product_Purchased__c = customer.product,
            Brochure_Key__c = customer.brochureKey,
            Brochure_URL__c = customer.brochureUrl,
            CAID__c = customer.caid,
            Customer_Id__c = customer.paymentDetails.customerId,
            Payment_Successful__c = paymentSuccessful,
            Payment_Type__c = customer.paymentDetails.paymentType,
            Payment_Frequency__c = customer.paymentDetails.paymentFrequency
        );

        if( !String.isBlank(customer.address.addressLine2) ){
            newContact.MailingStreet = customer.address.addressLine1 + ' ' + customer.address.addressLine2;
        } else {
            newContact.MailingStreet = customer.address.addressLine1;
        }

        Id olsRecordTypeId = OnlineStoreCustomerHelper.getRecordTypeId('Online_Store_Customer');

        if( olsRecordTypeId != null ){
            newContact.RecordTypeId = olsRecordTypeId;
        }

        return newContact;
    }

/**
* CLASSES
*/
    // this is the exact format we are expecting for a customer object from the DDMN WebApps Online Store
    
    public class ClientSideCustomer {
        public String firstName {get;set;}
        public String lastName {get;set;}
        public String email {get;set;}
        public AddressData address {get;set;}
        public String phone {get;set;}
        public String product {get;set;}
        public String brochureKey {get;set;}
        public String brochureUrl {get;set;}
        public String caid {get;set;}
        public PaymentDetails paymentDetails {get;set;}
    }

    public class AddressData {
        public String addressLine1 {get;set;}
        public String addressLine2 {get;set;}
        public String city {get;set;}
        public String state {get;set;}
        public String zip {get;set;}
    }

    public class PaymentDetails {
        public String paymentSuccessful {get;set;}
        public String paymentType {get;set;}
        public String customerId {get;set;}
        public String paymentAuthNumber {get;set;}
        public String bankAccountType {get;set;}
        public String paymentFrequency {get;set;}
        public String callingApplication {get;set;}
        public String paymentErrorMessage {get;set;}
    }
}